// This is main layout page where our components gets rendered.


import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import connectDB from '@/dbConfig/dbConfig'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  connectDB()
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <p>Hello from Prayash Mishra</p>
      </body>
    </html>
  )
}
